import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import axios from 'axios'
import './styles.css'

type Staff = { id:string; name:string; slug:string }
type Service = { id:string; name:string; description?:string; duration_minutes:number; staff_member_id:string }
type Slot = { start_at:string; end_at:string }
type Booking = { id:string; status:string; start_at:string; end_at:string; timezone:string; customer_name:string; service:Service; staff_member:Staff }
const api = axios.create({ baseURL: '/api' })
const dateToday = new Date().toLocaleDateString('en-CA', { timeZone:'America/Mexico_City' })

function App() {
  const [staff, setStaff] = useState<Staff[]>([]); const [selected, setSelected] = useState<Staff>(); const [service, setService] = useState<Service>();
  const [date, setDate] = useState(dateToday); const [slots, setSlots] = useState<Slot[]>([]); const [slot, setSlot] = useState<Slot>(); const [booking, setBooking] = useState<Booking>(); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  useEffect(()=>{ api.get<Staff[]>('/staff').then(r=>setStaff(r.data)).catch(()=>setError('No fue posible cargar la agenda.')) }, [])
  useEffect(()=>{ if (!selected) return; setService(undefined); setSlot(undefined); api.get<Service[]>('/services',{params:{staff_slug:selected.slug}}).then(r=>setService(r.data[0])) },[selected])
  useEffect(()=>{ if (!service) return; setLoading(true); api.get<{slots:Slot[]}>('/availability',{params:{service_id:service.id,date,timezone:'America/Mexico_City'}}).then(r=>setSlots(r.data.slots)).catch(()=>setError('No fue posible consultar horarios.')).finally(()=>setLoading(false)) },[service,date])
  async function submit(event:React.FormEvent<HTMLFormElement>) { event.preventDefault(); if(!selected||!service||!slot)return; const form=new FormData(event.currentTarget); setLoading(true); setError(''); try { const result=await api.post<Booking>('/appointments',{staff_member_id:selected.id,service_id:service.id,start_at:slot.start_at,timezone:'America/Mexico_City',customer:{name:form.get('name'),email:form.get('email'),phone:form.get('phone')},notes:form.get('notes')}); setBooking(result.data) } catch { setError('El horario ya no está disponible o no pudimos confirmar la cita. Intenta otro horario.') } finally {setLoading(false)} }
  if(booking) return <main className="shell confirmation"><p className="eyebrow">ATLAS BOOKING</p><span className="check">✓</span><h1>Tu cita está confirmada.</h1><p>{booking.customer_name}, te esperamos para tu {booking.service.name.toLowerCase()} con {booking.staff_member.name}.</p><div className="card"><b>{new Intl.DateTimeFormat('es-MX',{dateStyle:'full',timeStyle:'short',timeZone:booking.timezone}).format(new Date(booking.start_at))}</b><span>{booking.service.duration_minutes} minutos · {booking.timezone}</span></div></main>
  return <main className="shell"><header><p className="eyebrow">ATLAS BOOKING</p><h1>Tu tiempo merece<br/>un buen espacio.</h1><p className="lead">Elige a tu profesional y reserva una consulta en pocos pasos.</p></header>{error&&<p className="error">{error}</p>}<section><p className="step">01 — ELIGE A TU PROFESIONAL</p><div className="people">{staff.map(person=><button key={person.id} className={'person '+(selected?.id===person.id?'active':'')} onClick={()=>setSelected(person)}><span className="avatar">{person.name[0]}</span><span>{person.name}</span><small>Ver disponibilidad</small></button>)}</div></section>{selected&&service&&<section><p className="step">02 — FECHA Y HORARIO</p><div className="card"><strong>{service.name}</strong><span>{service.duration_minutes} minutos</span><input aria-label="Fecha" type="date" min={dateToday} value={date} onChange={e=>setDate(e.target.value)}/><div className="slots">{loading?<p>Consultando agenda…</p>:slots.length?slots.map(item=><button className={slot?.start_at===item.start_at?'active':''} key={item.start_at} onClick={()=>setSlot(item)}>{new Intl.DateTimeFormat('es-MX',{hour:'2-digit',minute:'2-digit',timeZone:'America/Mexico_City'}).format(new Date(item.start_at))}</button>):<p>No hay horarios disponibles este día.</p>}</div></div></section>}{slot&&<section><p className="step">03 — TUS DATOS</p><form className="card" onSubmit={submit}><input required name="name" placeholder="Nombre completo"/><input required name="phone" placeholder="Teléfono / WhatsApp"/><input required type="email" name="email" placeholder="Correo electrónico"/><textarea name="notes" placeholder="Notas (opcional)"/><button className="primary" disabled={loading}>{loading?'Confirmando…':'Confirmar cita'}</button></form></section>}<footer>Horarios en America/Mexico_City</footer></main>
}
createRoot(document.getElementById('root')!).render(<App />)
